import {
  Calendar,
  Clock,
  Eye,
  EyeOff,
  FileText,
  HardHat,
  Home,
  Image,
  Layers,
  Lock,
  Mail,
  Package,
  Percent,
  Phone,
  RulerDimensionLine,
  Search,
  SearchX,
  Tags,
  User,
  Wallet,
  Waypoints,
  Wrench,
} from "lucide-react";

export const iconMap = {
  eye: Eye,
  eyeClose: EyeOff,
  mail: Mail,
  lock: Lock,
  user: User,
  search: Search,
  searchX: SearchX,
  wallet: Wallet,
  fileText: FileText,
  image: Image,
  layers: Layers,
  tags: Tags,
  hardHat: HardHat,
  ruler: RulerDimensionLine,
  package: Package,
  wrench: Wrench,
  phone: Phone,
  waypoints: Waypoints,
  home: Home,
  calendar: Calendar,
  clock: Clock,
  percent: Percent,
} as const;

export type IconName = keyof typeof iconMap;
